### ISSUE TITLE
Use version ranges for dependencies

### ISSUE THREAD

**Issue by djmattyg007** [bent10/glob-reader#12]
Renovatebot has upgraded my project's dependency of `vfile` from `5.3.2` to `5.3.3`, but now I have two versions of `vfile` installed. This is because the latest release of `glob-reader` depends specifically on `5.3.2`.

If `glob-reader` instead used `^5.3.2` (or `^5.3.3`), I would only have one version installed.

**Comment by bent10** [comment]
Our `semantic-release` bot has released [v1.3.2](https://github.com/bent10/glob-reader/releases/tag/v1.3.2) with [`"vfile": "v5.3.3"`](https://github.com/bent10/glob-reader/commit/de924454fe93139b49fc3eae64e8aa0e3bc9880e).

**Comment by djmattyg007** [comment]
But it's still hard-coded to use a specific version. If/when `vfile` `v5.3.4` comes along, the same issue will be present.

This seems to apply to all of this package's dependencies.
